import type { Interview } from "./types";

function isoDaysFromNow(days: number, hour = 15, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export function sampleInterviews(): Interview[] {
  const now = new Date().toISOString();
  return [
    {
      id: "sample-stripe",
      gmailThreadId: "sample-thread-stripe",
      gmailMessageId: "sample-msg-stripe",
      companyName: "Stripe",
      role: "Staff Product Engineer",
      status: "Scheduled",
      interviewDate: isoDaysFromNow(4, 14, 30),
      interviewerNames: ["Amina Chen", "Luis Ortega"],
      meetingLink: "https://zoom.us/j/847291003",
      subject: "Stripe — interview scheduled with Product Eng",
      snippet:
        "Looking forward to speaking with you Thursday. We'll cover system design, then a product walkthrough.",
      source: "sample",
      notes: "Loop is 75 minutes. Prepare a recent incident write-up.",
      lastEmailAt: isoDaysFromNow(-2, 9, 12),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sample-figma",
      gmailThreadId: "sample-thread-figma",
      gmailMessageId: "sample-msg-figma",
      companyName: "Figma",
      role: "Senior Frontend Engineer",
      status: "Scheduled",
      interviewDate: isoDaysFromNow(1, 11, 0),
      interviewerNames: ["Priya Shah"],
      meetingLink: "https://meet.google.com/kqm-fwts-abn",
      subject: "Figma interview: hiring manager screen",
      snippet: "Please join the Google Meet link below. Duration: 45 minutes.",
      source: "sample",
      notes: null,
      lastEmailAt: isoDaysFromNow(-1, 16, 40),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sample-notion",
      gmailThreadId: "sample-thread-notion",
      gmailMessageId: "sample-msg-notion",
      companyName: "Notion",
      role: "Engineering Manager",
      status: "Completed",
      interviewDate: isoDaysFromNow(-5, 13, 0),
      interviewerNames: ["Jonah Park", "Elena Voss"],
      meetingLink: null,
      subject: "Thanks for interviewing with Notion",
      snippet: "Appreciate you taking the time for the onsite yesterday. We'll be in touch.",
      source: "sample",
      notes: "Panel went long. Strong on team rituals, weaker on infra story.",
      lastEmailAt: isoDaysFromNow(-4, 10, 5),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sample-linear",
      gmailThreadId: "sample-thread-linear",
      gmailMessageId: "sample-msg-linear",
      companyName: "Linear",
      role: "Full-Stack Engineer",
      status: "Offer",
      interviewDate: isoDaysFromNow(-12, 15, 0),
      interviewerNames: ["Karri Saarinen"],
      meetingLink: null,
      subject: "Offer from Linear",
      snippet: "We're excited to offer you the Full-Stack Engineer role on the workflow team.",
      source: "sample",
      notes: "Verbal offer; written letter expected this week.",
      lastEmailAt: isoDaysFromNow(-1, 8, 20),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sample-vercel",
      gmailThreadId: "sample-thread-vercel",
      gmailMessageId: "sample-msg-vercel",
      companyName: "Vercel",
      role: "Platform Engineer",
      status: "Rejected",
      interviewDate: isoDaysFromNow(-18, 10, 0),
      interviewerNames: ["Recruiting team"],
      meetingLink: null,
      subject: "Update on your application to Vercel",
      snippet:
        "After careful review we will not be moving forward. Thank you for your time.",
      source: "sample",
      notes: null,
      lastEmailAt: isoDaysFromNow(-9, 12, 0),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "sample-anthropic",
      gmailThreadId: "sample-thread-anthropic",
      gmailMessageId: "sample-msg-anthropic",
      companyName: "Anthropic",
      role: "Research Engineer",
      status: "Canceled",
      interviewDate: isoDaysFromNow(2, 16, 0),
      interviewerNames: ["Maya Ellison"],
      meetingLink: "https://zoom.us/j/120984433",
      subject: "Interview canceled — Anthropic",
      snippet: "We need to reschedule the research-scope conversation. Apologies for the late notice.",
      source: "sample",
      notes: "Waiting on a new slot.",
      lastEmailAt: isoDaysFromNow(-0.2, 18, 10),
      createdAt: now,
      updatedAt: now,
    },
  ];
}
